# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#

arts_category = Category.create(name: "Arts")
Category.create(name: "Books", parent: arts_category)
Category.create(name: "Design", parent: arts_category)
Category.create(name: "Fashion & Beauty", parent: arts_category)
Category.create(name: "Food", parent: arts_category)
Category.create(name: "Performing Arts", parent: arts_category)
Category.create(name: "Visual Arts", parent: arts_category)

business_category = Category.create(name: "Business")
Category.create(name: "Careers", parent: business_category)
Category.create(name: "Entrepreneurship", parent: business_category)
Category.create(name: "Investing", parent: business_category)
Category.create(name: "Management", parent: business_category)
Category.create(name: "Marketing", parent: business_category)
Category.create(name: "Non-Profit", parent: business_category)

comedy_category = Category.create(name: "Comedy")
Category.create(name: "Comedy Interviews", parent: comedy_category)
Category.create(name: "Improv", parent: comedy_category)
Category.create(name: "Stand-Up", parent: comedy_category)

education_category = Category.create(name: "Education")
Category.create(name: "Courses", parent: education_category)
Category.create(name: "How To", parent: education_category)
Category.create(name: "Language Learning", parent: education_category)
Category.create(name: "Self-Improvement", parent: education_category)


fiction_category = Category.create(name: "Fiction")
Category.create(name: "Comedy Fiction", parent: fiction_category)
Category.create(name: "Drama", parent: fiction_category)
Category.create(name: "Science Fiction", parent: fiction_category)

Category.create(name: "Government")
Category.create(name: "History")

health_fitness_category = Category.create(name: "Health & Fitness")
Category.create(name: "Alternative Health", parent: health_fitness_category)
Category.create(name: "Fitness", parent: health_fitness_category)
Category.create(name: "Medicine", parent: health_fitness_category)
Category.create(name: "Mental Health", parent: health_fitness_category)
Category.create(name: "Nutrition", parent: health_fitness_category)
Category.create(name: "Sexuality", parent: health_fitness_category)

kids_family_category = Category.create(name: "Kids & Family")
Category.create(name: "Education for Kids", parent: kids_family_category)
Category.create(name: "Parenting", parent: kids_family_category)
Category.create(name: "Pets & Animals", parent: kids_family_category)
Category.create(name: "Stories for Kids", parent: kids_family_category)

leisure_category = Category.create(name: "Leisure")
Category.create(name: "Animation & Manga", parent: leisure_category)
Category.create(name: "Automotive", parent: leisure_category)
Category.create(name: "Aviation", parent: leisure_category)
Category.create(name: "Crafts", parent: leisure_category)
Category.create(name: "Games", parent: leisure_category)
Category.create(name: "Hobbies", parent: leisure_category)
Category.create(name: "Home & Garden", parent: leisure_category)
Category.create(name: "Video Games", parent: leisure_category)

music_category = Category.create(name: "Music")
Category.create(name: "Music Commentary", parent: music_category)
Category.create(name: "Music History", parent: music_category)
Category.create(name: "Music Interviews", parent: music_category)

news_category = Category.create(name: "News")
Category.create(name: "Business News", parent: news_category)
Category.create(name: "Daily News", parent: news_category)
Category.create(name: "Entertainment News", parent: news_category)
Category.create(name: "News Commentary", parent: news_category)
Category.create(name: "Politics", parent: news_category)
Category.create(name: "Sports News", parent: news_category)
Category.create(name: "Tech News", parent: news_category)

religion_spirituality_category = Category.create(name: "Religion & Spirituality")
Category.create(name: "Buddhism", parent: religion_spirituality_category)
Category.create(name: "Christianity", parent: religion_spirituality_category)
Category.create(name: "Hinduism", parent: religion_spirituality_category)
Category.create(name: "Islam", parent: religion_spirituality_category)
Category.create(name: "Judaism", parent: religion_spirituality_category)
Category.create(name: "Religion", parent: religion_spirituality_category)
Category.create(name: "Spirituality", parent: religion_spirituality_category)

science_category = Category.create(name: "Science")
Category.create(name: "Astronomy", parent: science_category)
Category.create(name: "Chemistry", parent: science_category)
Category.create(name: "Earth Sciences", parent: science_category)
Category.create(name: "Life Sciences", parent: science_category)
Category.create(name: "Mathematics", parent: science_category)
Category.create(name: "Natural Sciences", parent: science_category)
Category.create(name: "Nature", parent: science_category)
Category.create(name: "Physics", parent: science_category)
Category.create(name: "Social Sciences", parent: science_category)

society_culture_category = Category.create(name: "Society & Culture")
Category.create(name: "Documentary", parent: society_culture_category)
Category.create(name: "Personal Journals", parent: society_culture_category)
Category.create(name: "Philosophy", parent: society_culture_category)
Category.create(name: "Places & Travel", parent: society_culture_category)
Category.create(name: "Relationships", parent: society_culture_category)

sports_category = Category.create(name: "Sports")
Category.create(name: "Baseball", parent: sports_category)
Category.create(name: "Basketball", parent: sports_category)
Category.create(name: "Cricket", parent: sports_category)
Category.create(name: "Fantasy Sports", parent: sports_category)
Category.create(name: "Football", parent: sports_category)
Category.create(name: "Golf", parent: sports_category)
Category.create(name: "Hockey", parent: sports_category)
Category.create(name: "Rugby", parent: sports_category)
Category.create(name: "Running", parent: sports_category)
Category.create(name: "Soccer", parent: sports_category)
Category.create(name: "Swimming", parent: sports_category)
Category.create(name: "Tennis", parent: sports_category)
Category.create(name: "Volleyball", parent: sports_category)
Category.create(name: "Wilderness", parent: sports_category)
Category.create(name: "Wrestling", parent: sports_category)

Category.create(name: "Technology")
Category.create(name: "True Crime")

tv_film_category = Category.create(name: "TV & Film")
Category.create(name: "After Shows", parent: tv_film_category)
Category.create(name: "Film History", parent: tv_film_category)
Category.create(name: "Film Interviews", parent: tv_film_category)
Category.create(name: "Film Reviews", parent: tv_film_category)
Category.create(name: "TV Reviews", parent: tv_film_category)

# Podcasts
Podcast.create(title: 'The Joe Rogan Experience', rss: 'http://joeroganexp.joerogan.libsynpro.com/rss', itunes_image: 'not_available')
Podcast.create(title: 'The Daily', rss: 'https://rss.art19.com/the-daily', itunes_image: 'not_available')
Podcast.create(title: 'Grumpy Old Geeks', rss: 'https://grumpyoldgeeks.libsyn.com/rss', itunes_image: 'not_available')
Podcast.create(title: 'The Tim Ferriss Show', rss: 'https://rss.art19.com/tim-ferriss-show', itunes_image: 'not_available')
Podcast.create(title: 'Planet Money', rss: 'https://www.npr.org/rss/podcast.php?id=510289', itunes_image: 'not_available')
Podcast.create(title: 'Accidental Tech Podcast', rss: 'https://atp.fm/episodes?format=rss', itunes_image: 'not_available')
Podcast.create(title: 'The Ezra Klein Show', rss: 'https://feeds.megaphone.fm/theezrakleinshow', itunes_image: 'not_available')
Podcast.create(title: 'Hidden Brain', rss: 'https://www.npr.org/rss/podcast.php?id=510308', itunes_image: 'not_available')
Podcast.create(title: 'Stuff You Should Know', rss: 'https://feeds.megaphone.fm/stuffyoushouldknow', itunes_image: 'not_available')
Podcast.create(title: 'The Art of Manliness', rss: 'https://rss.art19.com/art-of-manliness', itunes_image: 'not_available')
